<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <h1>OPERACIONES</h1>
    <Br>
    <p></p>
    <form action="MAYUS.PHP"method="get">
        <label>Digite un numero </label>
        <input type="number" name="operacion"><br>
        <label> Digite segundo numero </label>
        <input type="number" name="operacion"><br>
        <label>Operacion:</label>
        <input type="text" name="operacion"><br>

    <input type="submit" name="btn_enviar" value="ejecutar">
    
    </body>
</html>